[build]
  functions = "functions"
  command = "npm run build"
  publish = "public"
  environment = { NODE_VERSION = "14" } # Specify the desired Node.js version

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/:splat"
